install:
- pip install -U pip
- pip install cookiecutter
- pip --version
- ( cd modint && cat requirements_dev.txt )
# - ( cd modint && pip install -r requirements.txt && pip install . )
- ( cd modint && pip install -r requirements_dev.txt )
language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- pypy3
script:
- ( cd modint && py.test --cov zenfilter --cov-report term-missing tests/ )
- ( cd modint && py.test )
